ifeq ($(USE_PVR_VIDEO), true)
LOCAL_PATH := $(call my-dir)
EXTERNAL_KERNEL_MODULES += $(LOCAL_PATH)
include $(CLEAR_VARS)
LOCAL_MODULE := vxd392
LOCAL_MODULE_PATH := $(LOCAL_PATH)
LOCAL_CONFIG_OVERRIDE_FILES := config_flags.txt
include $(BUILD_EXTERNAL_KERNEL_MODULE)
endif
